### ISSUE TITLE
Add system state 97 (Safety discharge)

### ISSUE THREAD

**Issue by DSchndr** [mchwalisz/home-assistant-senec#26]
Integration crashes with
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/senec/__init__.py", line 116, in state
    value = getattr(self.coordinator.senec, sensor)
  File "/usr/local/lib/python3.9/site-packages/pysenec/__init__.py", line 22, in system_state
    return SYSTEM_STATE_NAME[value]
KeyError: 97`

After the latest senec update, display shows "Safety discharge"

**Comment by JoJa1101** [comment]
After latest SENEC FW i am getting every day in the morning this error:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/senec/__init__.py", line 116, in state
    value = getattr(self.coordinator.senec, sensor)
  File "/usr/local/lib/python3.9/site-packages/pysenec/__init__.py", line 22, in system_state
    return SYSTEM_STATE_NAME[value]
KeyError: 95

**Comment by mchwalisz** [comment]
that is a pysenec problem mchwalisz/pysenec#6 will be fixed with new version.

**Comment by JoJa1101** [comment]
@mchwalisz Do you merge it into Version 2.0.2?

**Comment by neubi4** [comment]
@mchwalisz is it possible to release a new version of pysenec and the ha integration to fix this issue?

The integration works really well, but not having data for an hour every day while battery diagnose is running is a bit annoying and also provides inaccurate statistics to the energy panel.

I also would love to see #25 and mchwalisz/pysenec#9 merged to have even more data in home assistant.

If you need any help i can try to support you.

**Comment by mchwalisz** [comment]
should be fixed now.
