### ISSUE TITLE
Frequently "not available" error since some days (HA update 2022.10?)

### ISSUE THREAD

**Issue by klaus1956** [mchwalisz/home-assistant-senec#35]
Hello
I ran the intergartion some months now w/o problems on a modified timedelta of 20 seconds instead of the original 60 seconds. More or less since the HA-update to 2022.10 I got frequently not available errors . Even after re-adjusting timedelta to 60 secondes the measurement data are not available for more than 50% of the time.

PV-Car charging is not possible under these conditions :(

Has anyone else the same issue?

**Comment by s50en** [comment]
I have exactly the same issues... now i just added a cronjob to home assitant that it will be automaticall restarted every night .....But the root cause is on the addon i am pretty sure

**Comment by klaus1956** [comment]
Meanwhile I have the feeling that this is somehow linked to a fragile network cable connection.
In-between I had some days w/o any problem and today I had the failure mode again.

**Comment by mchwalisz** [comment]
Could you share the logs and detailed error messages you get? You should have something if the sensors are not available?

I do not experience any problems even with latest HA, so it's hard for me to judge.

**Comment by Basti-Fantasti** [comment]
I'm having the same issue here. Since a few HA updates, the integration says "not available".
Removing and re-adding the integration does not work. Only restarting Home Assistant fixes the issue.

Where can I find some debug logouts which could help to find the source of the problem?

**Comment by Basti-Fantasti** [comment]
lately it seems to be more stable again. I'm on the current HA 2023.3.6 version.

**Comment by xibix-fp** [comment]
I am currently getting the same issue in the version 2023.8.1.
The logs show:

`2023-08-15 21:34:31.297 ERROR (MainThread) [custom_components.senec] Unexpected error fetching senec data: unexpected character: line 1 column 1009 (char 1008)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/senec/__init__.py", line 66, in _async_update_data
    await self.senec.update()
  File "/usr/local/lib/python3.11/site-packages/pysenec/__init__.py", line 194, in update
    await self.read_senec_v21()
  File "/usr/local/lib/python3.11/site-packages/pysenec/__init__.py", line 239, in read_senec_v21
    self._raw = parse(await res.json())
                      ^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 73, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1120, in json
    return loads(stripped.decode(encoding))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 1 column 1009 (char 1008)`

**Comment by klaus1956** [comment]
For me the problem seems to be solved locally.
My SENEC is connected to a WiFi-Access point and after improving the WiFi in general and changing the AP from a **Fritz!box 7490** to a **Fritz!Repeater 3000** things seem to work smooth.

**Comment by Basti-Fantasti** [comment]
I have no issues with the integration running the latest HA Version 2023.8.3

Running like a charm (except that the battery is again in 70% conditioning mode 😢 )

**Comment by xibix-fp** [comment]
Anyone an idea how to validate the issue? Looks for me, that the response of the API Call returns an unexpected character. Does anyone knows the exact API call?

**Comment by xibix-fp** [comment]
@klaus1956 Why did you closed this issue? Looks like the problem does still exist?

**Comment by klaus1956** [comment]
I think I opened it due to a specific issue (on my side) which is solved
But if there is still a need I reopen it
